### ISSUE TITLE
Game Plan

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sunfish#1]
I would like the first iteration of Sunfish to be ready by June 21st, 2015. That's not a whole lot of time, and for the most part only one person is going to be working on it, so the feature set needs to be picked carefully.

The idea is that there's a view or a plugin in the UI that can talk to a sunfish server. The default sunfish server will be one that's managed by Nebulous, but you can add and remove servers that you know about. You can upload files, search for files, and download files.

Files are searched for by string matching. All files for a given string are shown. We choose not to worry very much about security or spam for the time being. The default string suggested when you upload should be the hash of the file, and the name of the file. More strings can be added if desired. (exact match is required, but only on one of the strings).

Files are stored as their '.sia' files that can be created by the renter. Sunfish merely points to where other files exist, and gives people the '.sia' files (or their asciisia equivalents) when people ask for a download.

The default port for sunfish should be ":9983".

Does all this sound reasonable for the first 3 weeks?

**Comment by agundy** [comment]
Sounds reasonable. Just curious but what do you mean by the default port should be 9983? Isn't it a webserver? port 80 is the default port for websites

**Comment by DavidVorick** [comment]
It's not intended to be a website, at least initially. More like an api. A website can be built around that later.

**Comment by lukechampine** [comment]
I was thinking about plugins the other day too. The other application I had in mind was for the miner. So the standard client doesn't have a miner view, but you can install a plugin for it. This would encourage people to develop plugins for Sia-UI rather than their own standalone apps, at least for smaller projects.
