### ISSUE TITLE
anti-tags

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sunfish#13]
When you search for 'tags', it should bring up any files that have those tags. If a file has 5 tags and you only search for 1 of them, it should bring up that file.

When you search for 'anti-tags', it excludes all files with those tags. If a file has 5 tags and you search for 2 of them, but also anti-search for 1 of them, then the file is excluded.

The immediate use case would be 'nsfw', which would exclude all content tagged as 'nsfw'.

**Comment by agundy** [comment]
Was thinking, should we have nsfw as a separate tag that we can toggle as a binary? Would probably be faster as it would be one of the most used tags and is useful.

**Comment by DavidVorick** [comment]
That's how most sites do it. Anti-tags would be a good 'advanced' mode thing
