### ISSUE TITLE
Filesize

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sunfish#15]
Should be easy to list a file's size alongside its name + tags

**Comment by agundy** [comment]
Currently I don't have a way to decode the .sia file to a useful golang struct. Would be nice to have an encode decode module made available. Was discussing this with Taek.

**Comment by DavidVorick** [comment]
I can get something in a bit, but I've got a lot of other stuff that I need to focus on first. We're going to be redesigning the renter + host structures entirely though.
