### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sunfish#16]
it should be possible to order results by various criteria. Most obvious one is upload time, which I believe is the current practice. (However, more recent uploads should be listed at the top, not the bottom, don't you think?)

**Comment by lukechampine** [comment]
partially addressed by #20

**Comment by agundy** [comment]
Will add more sorting ability soon. will be simple.

**Comment by agundy** [comment]
Should come with ui changes though. Front end will start filling up fast without a redesign for files to have their own pages.
