### ISSUE TITLE
Figure out front end.

### ISSUE THREAD

**Issue by agundy** [NebulousLabs/Sunfish#3]
Options are to use Go templating or a frontend js framework, Go templating doesn't seem powerful enough and more difficult. Leaning more towards a completely static js frontend with separate API. 
JS Frontend Options:
- Angular.js
- Ember.js
- React.js 
- etc.

**Comment by DavidVorick** [comment]
I am okay using a js framework. I'm really picky about my frameworks though, would rather avoid anything that feels like 'flavor of the year' type stuff. Something with 3-5+ years of age, and lots of info on stackoverflow.

Sometimes we make exceptions, electron is a good example of this. Electron is everything I like to avoid, except that it was miles and miles ahead of the next best option, so we went with Electron.

Something that talks to a server api and then does all the processing and formatting client-side sounds more scalable anyway.

**Comment by DavidVorick** [comment]
I would consider this 'figured out enough' for the time being
